export default {
  genres: [

    // selected
    'rock',
    'electronic',
    'pop',
    'hip hop',
    'indie',
    'rap',
    'ambient',

    // all
    'acoustic',
    'african',
    'alt-country',
    'alternative',
    'americana',
    'atmospheric',
    'baby',
    'balkan',
    'baroque',
    'beat-tape',
    'beats',
    'bebop',
    'big band',
    'black metal',
    'bluegrass',
    'blues rock',
    'blues',
    'boogie',
    'boogie-woogie',
    'boom-bap',
    'brazilian',
    'breaks',
    'britpop',
    'celtic',
    'chamber music',
    'chill-out',
    'chillwave',
    'chiptune',
    'choral',
    'classical',
    'country',
    'crust punk',
    'cumbia',
    'dance',
    'dancehall',
    'dark ambient',
    'death metal',
    'deathcore',
    'deep funk',
    'delta blues',
    'doom',
    'downtempo',
    'dream pop',
    'drone',
    'drum & bass',
    'dub',
    'dubstep',
    'edm',
    'educational',
    'electric blues',
    'electro pop',
    'electro',
    'electro-acoustic',
    'electronica',
    'emo',
    'field recordings',
    'film music',
    'folk',
    'footwork',
    'free jazz',
    'funk jam',
    'funk rock',
    'funk',
    'fusion',
    'g-funk',
    'garage rock',
    'garage',
    'glitch',
    'go-go',
    'gospel',
    'goth',
    'grime',
    'grindcore',
    'grunge',
    'guitar',
    'gypsy',
    'hard rock',
    'hardcore punk',
    'hardcore',
    'heavy metal',
    'hillbilly',
    'honky-tonk',
    'house',
    'idm',
    'indie pop',
    'indie rock',
    'industrial',
    'instrumental',
    'j-pop',
    'jangle pop',
    'jazz funk',
    'jazz',
    'juke',
    'k-pop',
    'kids',
    'latin jazz',
    'lovers rock',
    'lullaby',
    'math rock',
    'meditation',
    'metal',
    'metalcore',
    'modern classical',
    'modern jazz',
    'motown',
    'music therapy',
    'neo-classical',
    'neo-soul',
    'new age',
    'new wave',
    'no wave',
    'noise pop',
    'nu jazz',
    'opera',
    'orchestral',
    'outlaw',
    'piano',
    'pop punk',
    'post hardcore',
    'post-hardcore',
    'post-punk',
    'post-rock',
    'power pop',
    'prog rock',
    'progressive metal',
    'psychedelic rock',
    'punk rock',
    'punk',
    'r&b',
    'ragga',
    'rare groove',
    'reggae',
    'reggaeton',
    'rhythm & blues',
    'rock & roll',
    'rockabilly',
    'rocksteady',
    'roots',
    'shoegaze',
    'singer-songwriter',
    'ska',
    'sludge metal',
    'soul jazz',
    'soul',
    'soundscapes',
    'soundtrack',
    'spiritual jazz',
    'surf rock',
    'swing',
    'synth pop',
    'synthwave',
    'techno',
    'thrash metal',
    'thrash',
    'trance',
    'trap',
    'tribal',
    'tropical',
    'urban',
    'vaporwave',
    'video game music',
    'vocal jazz',
    'western',
    'witch house',
    'world fusion',
    'world',
  ],
};
