export default {
  artists: [
    'Childish Gambino',
    'Diplo',
    'Drake',
    'Flume',
    'Gorillaz',
    'Hans Zimmer',
    'Louis The Child',
    'Lowercase Noises',
    'Major Lazer',
    'Massive Attack',
    'Odesza',
    'Ookay',
    'PETIT BISCUIT',
    'Porter Robinson',
    'Post Malone',
    'Pusha T',
    'Queen',
    'Rae Sremmurd',
    'RÜFÜS DU SOL',
    'San Holo',
    'The Weeknd',
    'The Who',
    'Tycho',
    'Whethan',
    'XXXTENTACION',
  ],
  genres: [
    '70s',
    '80s',
    '90s',
    'acoustic',
    'alternative rock',
    'alternative',
    'ambiant',
    'chillwave',
    'classic rock',
    'classical',
    'country',
    'dubstep',
    'edm',
    'electronic',
    'folk',
    'funk',
    'hiphop',
    'house',
    'indie folk',
    'indie rock',
    'indie',
    'instrumental',
    'jazz',
    'lo-fi',
    'metal',
    'piano',
    'pop punk',
    'pop',
    'progressive',
    'punk',
    'r&b',
    'rap',
    'reggae',
    'rock',
    'synthwave',
    'trap',
  ],
  modifiers: [
    'calm',
    'chill',
    'college',
    'cute',
    'dance',
    'drinking',
    'epic',
    'fanmix',
    'feel good',
    'focus',
    'high',
    'idk',
    'mashup',
    'mellow',
    'mix',
    'morning',
    'new',
    'night',
    'party',
    'rage',
    'reading',
    'relax',
    'remix',
    'sad',
    'sex',
    'sleep',
    'smoke',
    'soft',
    'study',
    'summer',
    'summertime',
    'weed',
    'winter',
    'workout',
    'writing',
  ],
};
