export default {
  activities: [
    'chill',
    'dance',
    'focus',
    'party',
    'rage',
    'sleep',
    'study',
    'work',
    'workout',
  ],
  artists: [
    'Childish Gambino',
    'Diplo',
    'Drake',
    'Flume',
    'Gorillaz',
    'Hans Zimmer',
    'Louis The Child',
    'Major Lazer',
    'Massive Attack',
    'Odesza',
    'Ookay',
    'PETIT BISCUIT',
    'Porter Robinson',
    'Post Malone',
    'Pusha T',
    'Queen',
    'Rae Sremmurd',
    'RÜFÜS DU SOL',
    'San Holo',
    'The Weeknd',
    'The Who',
    'Whethan',
    'XXXTENTACION',
  ],
  genres: [
    '70s',
    '80s',
    '90s',
    'alternative',
    'ambiant',
    'chillwave',
    'classical',
    'country',
    'dubstep',
    'edm',
    'electronic',
    'funk',
    'hiphop',
    'house',
    'indie',
    'jazz',
    'metal',
    'piano',
    'progressive',
    'punk',
    'rap',
    'reggae',
    'rock',
    'synthwave',
  ]
};
