export default {
  artists: [
    '2pac',
    'A$AP Ferg',
    'Alt-J',
    'Ariana Grande',
    'BROCKHAMPTON',
    'BTS',
    'Bad Bad Hats',
    'Beatles',
    'Bob Marley',
    'Bruno Mars',
    'Chance the Rapper',
    'Childish Gambino',
    'Coldplay',
    'Daft Punk',
    'Death Cab for Cutie',
    'Denzel Curry',
    'Dr. Dre',
    'Drake',
    'Ed Sheeran',
    'Elton John',
    'Fleetwood Mac',
    'Flume',
    'GUNSHIP',
    'Hans Zimmer',
    'J. Cole',
    'Jack Johnson',
    'Jay Z',
    'Joey Pecoraro',
    'Johnny Cash',
    'Kanye West',
    'Kendrick Lamar',
    'LCD Soundsystem',
    'Little People',
    'Louis The Child',
    'Lowercase Noises',
    'Mac Miller',
    'Major Lazer',
    'Mansionair',
    'Marvin Gaye',
    'Massive Attack',
    'Migos',
    'Modest Mouse',
    'Nirvana',
    'Nosaj Thing',
    'ODESZA',
    'Pixies',
    'Porter Robinson',
    'Post Malone',
    'Pusha T',
    'Queen',
    'Rage Against the Machine',
    'Red Hot Chili Peppers',
    'RÜFÜS DU SOL',
    'San Holo',
    'Sigur Rós',
    'Snoop Dogg',
    'Stevie Wonder',
    'TRAILS',
    'The Rolling Stones',
    'The Weeknd',
    'The Who',
    'Tycho',
    'Tyga',
    'Wiz Khalifa',
  ],
  genres: [
    '70s',
    '80s',
    '90s',
    'acoustic',
    'alternative',
    'ambiant',
    'chillwave',
    'classic rock',
    'classical',
    'country',
    'dancehall',
    'deep house',
    'drum & bass',
    'dubstep',
    'edm',
    'electronic',
    'folk',
    'funk',
    'hip-hop rap',
    'hip-hop',
    'house',
    'indie folk',
    'indie rock',
    'indie',
    'instrumental',
    'jazz',
    'lo-fi',
    'metal',
    'piano',
    'pop punk',
    'pop',
    'progressive',
    'punk',
    'r&b',
    'rap',
    'reggae',
    'rock',
    'soundtrack',
    'synthwave',
    'techno',
    'trance',
    'trap',
    'triphop',
  ],
  modifiers: [
    'calm',
    'chill',
    'college',
    'dance',
    'drinking',
    'epic',
    'fanmix',
    'focus',
    'high',
    'mashup',
    'mellow',
    'mix',
    'party',
    'rage',
    'reading',
    'relax',
    'remix',
    'sad',
    'sleep',
    'smoke',
    'study',
    'studying',
    'summer',
    'summertime',
    'weed',
    'winter',
    'workout',
    'writing',
  ],
};
